apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
  namespace: demo
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: kaniko-sa
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--dockerfile=/workspace/Dockerfile"
          - "--context=git://github.com/ankamarao1999/Pipeline-Testing.git"
          - "--destination=chaitanyaacr786543.azurecr.io/myapp:latest"
        env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker/