name: AKS CI-CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and Push Image to ACR
      run: |
        az acr build \
          --registry chaitanyaacr786543 \
          --image myapp:${{ github.sha }} .

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: my-rg
        cluster-name: my-aks

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/flask-app \
        flask-container=chaitanyaacr786543.azurecr.io/myapp:${{ github.sha }}
        kubectl rollout status deployment/flask-app
