name: Build & Deploy using Kaniko in AKS

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: AKS Auth
        run: |
          az aks get-credentials \
            --resource-group my-rg \
            --name my-aks \
            --overwrite-existing

      - name: Run Kaniko Build Job
        run: |
          kubectl apply -f k8s/kaniko-job.yaml
          kubectl wait --for=condition=complete job/kaniko-build -n demo --timeout=600s

      - name: Deploy Updated Image
        run: |
          kubectl apply -f k8s/deployment.yaml -n demo
